# This file was generated by GoReleaser. DO NOT EDIT.
cask "eng" do
  version "1.46.0"

  on_macos do
    on_arm do
      sha256 "bc91dcb2f4e6a19a6e44597fb3086904df91d2b9949a5ffe5ea21eb3d90d27fa"
      url "https://github.com/eng618/eng/releases/download/v#{version}/eng_#{version}_Darwin_arm64.tar.gz",
        verified: "github.com/eng618/eng"
    end
    on_intel do
      sha256 "79fa6b86170774228549270e1e3f7222048c228b5ecb664383035ff601ec824b"
      url "https://github.com/eng618/eng/releases/download/v#{version}/eng_#{version}_Darwin_x86_64.tar.gz",
        verified: "github.com/eng618/eng"
    end
  end
  on_linux do
    on_arm do
      sha256 "8450197b6b1daaeee951404ef0a4694d39a0dd7ba46661d9ebcdf4ae1e60c792"
      url "https://github.com/eng618/eng/releases/download/v#{version}/eng_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/eng618/eng"
    end
    on_intel do
      sha256 "ee97e2016e1f17c5353d44e313d79ebfb9b4a5ce9f81a2340ea55dedc33aec7d"
      url "https://github.com/eng618/eng/releases/download/v#{version}/eng_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/eng618/eng"
    end
  end

  name "eng"
  desc "Personal CLI to help facilitate my normal workflow"
  homepage "https://github.com/eng618/eng"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "eng"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/eng"]
    end
  end
  generate_completions_from_executable "eng", "completion",
    base_name: "eng",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required
end
