# This file was generated by GoReleaser. DO NOT EDIT.
cask "eng" do
  version "1.45.0"

  on_macos do
    on_arm do
      sha256 "1cb85914701b39b34cb00bcf53705a7a35d2d8731e9b50b1072d82cee4adfa0e"
      url "https://github.com/eng618/eng/releases/download/v#{version}/eng_#{version}_Darwin_arm64.tar.gz",
        verified: "github.com/eng618/eng"
    end
    on_intel do
      sha256 "1254aa7de9f7b4a442db7fa1ed91a7ee2b2dfc17a5db4140f81e4ad05284bea6"
      url "https://github.com/eng618/eng/releases/download/v#{version}/eng_#{version}_Darwin_x86_64.tar.gz",
        verified: "github.com/eng618/eng"
    end
  end
  on_linux do
    on_arm do
      sha256 "7f6a14b10ba7f4d90a4c0064e5074062820e4cfc2276573d9e6bc5fdfea2847e"
      url "https://github.com/eng618/eng/releases/download/v#{version}/eng_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/eng618/eng"
    end
    on_intel do
      sha256 "a8538bcded44888d59f5a2485bb8d3d9bfc9eaba318a30c60673cdb0f1e41ac8"
      url "https://github.com/eng618/eng/releases/download/v#{version}/eng_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/eng618/eng"
    end
  end

  name "eng"
  desc "Personal CLI to help facilitate my normal workflow"
  homepage "https://github.com/eng618/eng"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "eng"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/eng"]
    end
  end
  generate_completions_from_executable "eng", "completion",
    base_name: "eng",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required
end
