# This file was generated by GoReleaser. DO NOT EDIT.
cask "eng" do
  version "1.43.0"

  on_macos do
    on_intel do
      sha256 "56375da265c5884d62c0685732709b355e6ce6e3e3978862f6031978a8e94dfd"
      url "https://github.com/eng618/eng/releases/download/v#{version}/eng_#{version}_Darwin_x86_64.tar.gz",
        verified: "github.com/eng618/eng"
    end
    on_arm do
      sha256 "be97aba8816d1803685e1ec6b0c0b748c599ae3687098a4d7b0440aa3a170529"
      url "https://github.com/eng618/eng/releases/download/v#{version}/eng_#{version}_Darwin_arm64.tar.gz",
        verified: "github.com/eng618/eng"
    end
  end

  on_linux do
    on_intel do
      sha256 "094b7e475dcd2e90f1334de845962d38dd6703e88e2bd967857112d720138b7a"
      url "https://github.com/eng618/eng/releases/download/v#{version}/eng_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/eng618/eng"
    end
    on_arm do
      sha256 "7960fd1a3af0b0dfed87b1f0619a5418a51f80fa9a499cbeb3b801adb2261681"
      url "https://github.com/eng618/eng/releases/download/v#{version}/eng_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/eng618/eng"
    end
  end

  name "eng"
  desc "Personal CLI to help facilitate my normal workflow"
  homepage "https://github.com/eng618/eng"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "eng"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/eng"]
    end
  end
  generate_completions_from_executable "eng", "completion",
    base_name: "eng",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
