# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Eng < Formula
  desc "Personal CLI to help facilitate my normal workflow"
  homepage "https://github.com/eng618/eng"
  version "1.61.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/eng618/eng/releases/download/v1.61.0/eng_1.61.0_Darwin_x86_64.tar.gz"
      sha256 "a784d0dd38cf42757b95e19d64508e4fb72ea9365244b928c06bc35e23ac3f6b"

      define_method(:install) do
        bin.install "eng"
        generate_completions_from_executable(bin/"eng", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/eng618/eng/releases/download/v1.61.0/eng_1.61.0_Darwin_arm64.tar.gz"
      sha256 "b128dd57c6cff7ee5e4d362dcf44a5892f1d3c493d9eacd663674f28ec7c42df"

      define_method(:install) do
        bin.install "eng"
        generate_completions_from_executable(bin/"eng", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/eng618/eng/releases/download/v1.61.0/eng_1.61.0_Linux_x86_64.tar.gz"
      sha256 "e3b0f89d345de611b93d46fae136d6132a41e60c3ca847dc22d23e07caa5e977"
      define_method(:install) do
        bin.install "eng"
        generate_completions_from_executable(bin/"eng", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/eng618/eng/releases/download/v1.61.0/eng_1.61.0_Linux_arm64.tar.gz"
      sha256 "769ab026ebc85b9411d86aaf6037eb37886e8adeaf2de3e03a144dd3fd269a7e"
      define_method(:install) do
        bin.install "eng"
        generate_completions_from_executable(bin/"eng", "completion")
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/eng --version")
    assert_match "USAGE", shell_output("#{bin}/eng --help")
  end
end
