# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Eng < Formula
  desc "Personal CLI to help facilitate my normal workflow"
  homepage "https://github.com/eng618/eng"
  version "1.61.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/eng618/eng/releases/download/v1.61.2/eng_1.61.2_Darwin_x86_64.tar.gz"
      sha256 "14bcc72f72f83ebeb11375e50b10871394e44b1fa11144c29fb5b1fd465ced11"

      define_method(:install) do
        bin.install "eng"
        generate_completions_from_executable(bin/"eng", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/eng618/eng/releases/download/v1.61.2/eng_1.61.2_Darwin_arm64.tar.gz"
      sha256 "4b044493c356e985ecb79aec6367f3377c98a70281170241d8f34e70111d3272"

      define_method(:install) do
        bin.install "eng"
        generate_completions_from_executable(bin/"eng", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/eng618/eng/releases/download/v1.61.2/eng_1.61.2_Linux_x86_64.tar.gz"
      sha256 "a9e98bb752f3777228824515e52fe298839fa2635ae259d072a013983ab20eb4"
      define_method(:install) do
        bin.install "eng"
        generate_completions_from_executable(bin/"eng", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/eng618/eng/releases/download/v1.61.2/eng_1.61.2_Linux_arm64.tar.gz"
      sha256 "95a3f1bd342653ac879fbaefa7a7057407457e1fc85383fe53234b9ccf8e86a6"
      define_method(:install) do
        bin.install "eng"
        generate_completions_from_executable(bin/"eng", "completion")
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/eng --version")
    assert_match "USAGE", shell_output("#{bin}/eng --help")
  end
end
