# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Eng < Formula
  desc "Personal CLI to help facilitate my normal workflow"
  homepage "https://github.com/eng618/eng"
  version "1.48.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/eng618/eng/releases/download/v1.48.1/eng_1.48.1_Darwin_x86_64.tar.gz"
      sha256 "ca0961ee6709a6591963c46c173afb019580e28e48e450f2b83410bcd98c3cf9"

      define_method(:install) do
        bin.install "eng"
        generate_completions_from_executable(bin/"eng", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/eng618/eng/releases/download/v1.48.1/eng_1.48.1_Darwin_arm64.tar.gz"
      sha256 "f33537487852f665d838b9047b5bac8d07a96c4ddcbd18d241a2b22dd5b7410e"

      define_method(:install) do
        bin.install "eng"
        generate_completions_from_executable(bin/"eng", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/eng618/eng/releases/download/v1.48.1/eng_1.48.1_Linux_x86_64.tar.gz"
      sha256 "c8d69082493a9ab506763d398004a738cdf45da0c269048b18e38b6882d06b99"
      define_method(:install) do
        bin.install "eng"
        generate_completions_from_executable(bin/"eng", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/eng618/eng/releases/download/v1.48.1/eng_1.48.1_Linux_arm64.tar.gz"
      sha256 "75f7bba06f66c7308a3f898e23069c0a76f16297be463ae97a262945389ded37"
      define_method(:install) do
        bin.install "eng"
        generate_completions_from_executable(bin/"eng", "completion")
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/eng --version")
    assert_match "USAGE", shell_output("#{bin}/eng --help")
  end
end
